### ISSUE TITLE
Create a before_install_travis.sh and script_travis.sh scripts.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Kitura-Build#6]
In each `travis.yml` file we have in our repos, we have two main sections, `before_install` and `script`. To avoid code duplication across all of our `travis.yml` files, we can create two new scripts, `before_install_travis.sh` and `script_travis.sh` and check them in under this repo. Then each `travis.yml` file can simply invoke the corresponding script from those two sections.

**Comment by BDHernand** [comment]
ok to do this for the before_install section is going to be problematic.  The Kitura-Build directory 
will be empty until the git submodule init is done.  There would be no way to call into ./Kitura-Build/before_install_travis.sh because it would not be there until after the init.  The script one looks to be doable

**Comment by rolivieri** [comment]
Very true! Ok, let's then just do the `script` part.

**Comment by BDHernand** [comment]
Here are the devops repos to work on:

IBM-Swift/swift-ubuntu-docker
IBM-Bluemix/swift-helloworld
IBM-Swift/swift-runtime-container
IBM-Swift/kitura-ubuntu-docker
IBM-Swift/Swift-cfenv
IBM-Swift/swift-buildpack
IBM-Swift/Kitura-Build
IBM-Swift/BluePic
IBM-Swift/Kitura-Starter-Bluemix
IBM-Swift/Swift-Cloudand-Boilerplate
IBM-Swift/Devops

**Comment by BDHernand** [comment]
All repos so far are merged into develop and the travis builds are all passing.

**Comment by BDHernand** [comment]
We still need to update the Kitura repos
